# John Wick Quotes for Itomori

JOHN_WICK_QUOTES = [
    "I'm thinking I'm back!",
    "Everything's got a price.",
    "People keep asking if I'm back and I haven't really had an answer. But now, yeah, I'm thinking I'm back!",
    "John is a man of focus, commitment, sheer will...",
    "With a pencil! Who the f*** can do that?",
    "That 'nobody' is John Wick.",
    "He's the one you sent to kill the Boogeyman.",
    "I'll see you, John.",
    "You want a war, or do you just want to give me a gun?",
    "Freedom is a fight.",
    "Breathtaking!",
    "Fortune favors the bold.",
    "A man's life is only as good as the company he keeps.",
    "Consequences.",
    "I'll be seeing you.",
    "Tell them... tell them all. Whoever comes, whoever it is... I'll kill them. I'll kill them all.",
    "You dip so much as a pinky back into this pond... you may find something reaches out and drags you back into its depths.",
    "I'm not that guy anymore.",
    "Rules. Without them, we live with the animals.",
    "How good to see you again so soon.",
    "Si vis pacem, para bellum. (If you want peace, prepare for war.)",
    "Nothing's ever just a conversation with you, John.",
    "It wasn't just a dog.",
    "Be seeing you.",
    "They're going to see what I can do. I'm going to kill them all.",
    "I have no choice.",
    "May I suggest the Benelli M4?",
    "Rusty? I'm thinking I'm back.",
    "John, why are you here?",
    "A professional does not have to be told.",
    "Good to see you, John.",
    "It's been a long time, John.",
    "I'll kill them all.",
    "They killed my dog.",
    "I'm retired.",
    "I'm just a guy who wants to be left alone.",
    "I'm a man of my word.",
    "I'm not afraid of you.",
    "I'm not going to stop.",
    "I'm going to finish this."
]
